CREATE TABLE IF NOT EXISTS generated_plans (
    id SERIAL PRIMARY KEY,
    request_id VARCHAR(64),
    age INTEGER,
    gender VARCHAR(32),
    height FLOAT,
    weight FLOAT,
    fitness_goal VARCHAR(64),
    activity_level VARCHAR(64),
    experience_level VARCHAR(64),
    workout_location VARCHAR(64),
    dietary_preference VARCHAR(64),
    selection_mode VARCHAR(32),
    bmi FLOAT,
    bmi_category VARCHAR(64),
    daily_calorie_target FLOAT,
    macros_json JSONB,
    diet_plan_json JSONB,
    workout_plan_json JSONB,
    food_selection_json JSONB,
    raw_request_json JSONB,
    raw_response_json JSONB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
